#!/usr/bin/env bash

#alias git=hub
alias la='exa -abghl --git'
alias c='pygmentize -O style=monokai -f console256 -g'
alias clip="xclip -selection clipboard"
alias unclip="xclip -selection clipboard -o"
alias rainbow='yes "$(seq 231 -1 16)" | while read i; do printf "\x1b[48;5;${i}m\n"; sleep .02; done'
