#!/usr/bin/env bash

alias e="\$EDITOR"

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'

#alias git=hub
alias c="bat"
alias clip="xclip -selection clipboard"
alias unclip="xclip -selection clipboard -o"
alias rainbow='yes "$(seq 231 -1 16)" | while read i; do printf "\x1b[48;5;${i}m\n"; sleep .02; done'
