# Path to your oh-my-zsh installation.

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="spaceship"

CASE_SENSITIVE="false"

HYPHEN_INSENSITIVE="false"
PROMPT_EOL_MARK=
HIST_STAMPS="dd.mm.yyyy"
HIST_IGNORE_SPACE="true"
BROWSER="vivaldi-stable"

plugins=(
  git
  sudo
  httpie
  extract
  encode64
  archlinux
  command-not-found
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source ~/.shell_env
